name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Required to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.18'

    - name: Install dependencies
      run: |
        pip install mkdocs
        pip install mkdocs-material  # Optional: use if you're using the Material theme
        # pip install -r requirements.txt  # Uncomment if you have a requirements file

    - name: Deploy to GitHub Pages
      run: mkdocs gh-deploy --force
